### ISSUE TITLE
Log level

### ISSUE THREAD

**Issue by aura-tfn** [xadrianzetx/optuna-distributed#76]
Hi Adrian,

Thanks for this work. 

I  am using your API, but I cannot configure optuna log level. Every time I run a study, a lot of messages, for each try, fill the log no matter if I previously configure it :

   optuna.logging.disable_default_handler()
   optuna.logging.set_verbosity(optuna.logging.WARNING)
   optuna.logging.disable_propagation()

¿Is there a way to avoid it?

Thanks in advance
Aura

**Comment by xadrianzetx** [comment]
Hi!

That's because we're using our own log handler, which at the moment does not have a nice API to configure it. For the time being, you can use a workaround:
```python
import logging
import random
import time

import optuna
import optuna_distributed


def objective(trial):
    x = trial.suggest_float("x", -100, 100)
    y = trial.suggest_categorical("y", [-1, 0, 1])
    time.sleep(random.uniform(0.0, 2.0))
    return x**2 + y


if __name__ == "__main__":
    logging.getLogger("optuna_distributed").setLevel(logging.WARNING)
    optuna.logging.disable_default_handler()
    study = optuna_distributed.from_study(optuna.create_study())
    print("Running 10 trials...")
    study.optimize(objective, n_trials=10)
    print(f"Best value: {study.best_value} (params: {study.best_params})")

```
I'll try to introduce Optuna-like way to suppress log messages when there's more time.

**Comment by xadrianzetx** [comment]
Hi,

I've added optuna style logging helpers in [`0.5.0` release](https://pypi.org/project/optuna-distributed/0.5.0/). They can be used as follows:
```python
import random
import time

import optuna

import optuna_distributed


def objective(trial):
    x = trial.suggest_float("x", -100, 100)
    y = trial.suggest_categorical("y", [-1, 0, 1])
    time.sleep(random.uniform(0.0, 2.0))
    return x**2 + y


if __name__ == "__main__":
    optuna.logging.disable_default_handler()
    optuna_distributed.config.disable_logging()

    study = optuna_distributed.from_study(optuna.create_study())
    print("Running 10 trials without logging...")
    study.optimize(objective, n_trials=10)
    print(f"Best value: {study.best_value} (params: {study.best_params})")

    optuna_distributed.config.enable_logging()
    print("Running 10 more trials with logging...")
    study.optimize(objective, n_trials=10)
    print(f"Best value: {study.best_value} (params: {study.best_params})")

```

Note that logging is enabled by default, so there's no need to call `enable_logging` if `disable_logging` wasn't called before.
