### ISSUE TITLE
Windows support ?

### ISSUE THREAD

**Issue by championbruno** [xadrianzetx/optuna-distributed#93]
Hello,

I'm trying to run the example "README/**Basic example**" on Windows (Python 3.10, Windows 10, CPU AMD Ryzen7). 
I got en Exception _"Local asynchronous optimization is currently not supported on Windows. Please specify Dask client to continue in distributed mode."_.
Is there a simple solution to use optuna-distributed on Windows, on all available CPU cores on a local machine ?

Thanks for your help

**Comment by xadrianzetx** [comment]
You can set up local dask cluster by [following the example](https://distributed.dask.org/en/stable/quickstart.html#setup-dask-distributed-the-easy-way), and pass the resulting client to `optuna_distributed.from_study` like so:

```python
import optuna_distributed
from dask.distributed import Client

client = Client()
study = optuna_distributed.from_study(optuna.create_study(), client=client)
```

**Comment by championbruno** [comment]
Thank you for your quick answer.
I tested that but it's still not good : 

```
optuna_study = optuna.create_study(sampler=optuna.samplers.TPESampler(), pruner=optuna.pruners.HyperbandPruner())
dask_client = Client()
distributed_study = optuna_distributed.from_study(optuna_study, client = dask_client) 
the_study.optimize(...)
```
or that :
```
optuna_study = optuna.create_study(sampler=optuna.samplers.TPESampler(), pruner=optuna.pruners.HyperbandPruner())
dask_cluster =  dask.distributed.LocalCluster(n_workers = 4, host = '127.0.0.1')
dask_client = dask.distributed.Client(dask_cluster)                
distributed_study = optuna_distributed.from_study(optuna_study, client = dask_client) 
the_study.optimize(...)
```

=> Both raise (from `DistributedStudy.optimize()`) _"builtins.ValueError: Local asynchronous optimization is currently not supported on Windows. Please specify Dask client to continue in distributed mode."_

It seems that passing a `LocalCluster()` instance (or letting optuna/dask do it by default) on Windows is not possible right ?
https://github.com/xadrianzetx/optuna-distributed/blob/b78d56a4351c08b1052e4fce088fc7a68ef79640/optuna_distributed/study.py#L178-L188

**Comment by xadrianzetx** [comment]
In both of your snippets, you assign the dask-enabled study to `distributed_study`, but optimize something called `the_study`, which i suppose is causing the exception this time.

**Comment by championbruno** [comment]
Sorry for the back and forth, that's a typo when I copied/pasted the pieces of code : I confirm that I called `distributed_study.optimize()` and that `distributed_study `is well an instance coming from `optuna_distributed`:
```
type(distributed_study)
<class 'optuna_distributed.study.DistributedStudy'>
```

So here are the correct ones that raise the Exception, just for the sake of accuracy:
```
optuna_study = optuna.create_study(sampler=optuna.samplers.TPESampler(), pruner=optuna.pruners.HyperbandPruner())
dask_client = Client()
distributed_study = optuna_distributed.from_study(optuna_study, client = dask_client) 
distributed_study.optimize(...)
```


```
optuna_study = optuna.create_study(sampler=optuna.samplers.TPESampler(), pruner=optuna.pruners.HyperbandPruner())
dask_cluster =  dask.distributed.LocalCluster(n_workers = 4, host = '127.0.0.1')
dask_client = dask.distributed.Client(dask_cluster)                
distributed_study = optuna_distributed.from_study(optuna_study, client = dask_client) 
distributed_study.optimize(...)
```

**Comment by xadrianzetx** [comment]
Thanks for the clarification. I'll push the patch soon that enables dask `LocalCluster` usage on Windows.

**Comment by championbruno** [comment]
Cool, thank you

**Comment by xadrianzetx** [comment]
So, I've remembered why `LocalCluster` is disabled in distributed study and it has to do with problematic cleanup when the scheduler runs in the same process as  user code. Because of this, I will not enable the functionality at this time.

However, the workaround for windows optimization is still simple - just spawn the scheduler and workers in separate processes, for example by following [this document](https://docs.dask.org/en/stable/deploying-cli.html#command-line). Then you can point your client at it:

```python
client = Client("tcp://192.168.0.4:8786")
study = optuna_distributed.from_study(optuna.create_study(), client=client)
```

**Comment by championbruno** [comment]
Thanks, I will do that

**Comment by xadrianzetx** [comment]
The question has been answered, so I'm gonna close this one. Feel free to open a new issue if there are any more questions.
